### ISSUE TITLE
Not able to access S3 bucket when running Spark in client mode

### ISSUE THREAD

**Issue by tusharm** [aws-samples/amazon-eks-apache-spark-etl-sample#2]
Hi,

Instead of attaching the IAM policy directly to the worker nodes, couldn't we [associate](https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html) it with the service account `spark` or is that not sufficient?

I am trying to run my Spark job on EKS, **in client mode**. However, its not able to access data in my S3 bucket. Interestingly, when I run it using `--master local[*]`, it works fine.  I strongly suspect that the executor pods are not getting the credentials from service account, even though I am passing the service account as `--conf spark.kubernetes.authenticate.serviceAccountName=<my-service-account>` to `spark-submit` (as documented [here](https://spark.apache.org/docs/latest/running-on-kubernetes.html#spark-properties)). 

This is the error I get:
```
Caused by: java.lang.NullPointerException: You must specify a value for roleArn and roleSessionName
	at com.amazonaws.auth.STSAssumeRoleSessionCredentialsProvider$Builder.<init>(STSAssumeRoleSessionCredentialsProvider.java:359)
	at com.amazonaws.services.securitytoken.internal.STSProfileCredentialsService.getAssumeRoleCredentialsProvider(STSProfileCredentialsService.java:31)
	at com.amazonaws.auth.profile.internal.securitytoken.STSProfileCredentialsServiceProvider.getProfileCredentialsProvider(STSProfileCredentialsServiceProvider.java:39)
	at com.amazonaws.auth.profile.internal.securitytoken.STSProfileCredentialsServiceProvider.getCredentials(STSProfileCredentialsServiceProvider.java:71)
	at com.amazonaws.auth.WebIdentityTokenCredentialsProvider.getCredentials(WebIdentityTokenCredentialsProvider.java:76)
	at org.apache.hadoop.fs.s3a.AWSCredentialProviderList.getCredentials(AWSCredentialProviderList.java:129)
```
The stacktrace shows that `STSAssumeRoleSessionCredentialsProvider` class is used, instead of `STSAssumeRoleWithWebIdentitySessionCredentialsProvider`, probably because WebIdentityToken file path is not found [here](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-sts/src/main/java/com/amazonaws/services/securitytoken/internal/STSProfileCredentialsService.java#L30).

Am I missing something?

Tx!

EKS Cluster v1.15
Spark 2.4.5
Hadoop-AWS 2.9.2

**Comment by tusharm** [comment]
I think I've found the issue affecting me - https://issues.apache.org/jira/browse/SPARK-27872 - this was fixed in Spark 3.0.0. Hopefully, with this, I won't need to set the IAM policy at the managed node group level.

**Comment by vgkowski** [comment]
Are you trying to use IAM role for service accounts? S3A connector is not actually compatible with IAM role service account because it's using AWS SDK in a version older than the minimal requirement for IAM role for service account

**Comment by vgkowski** [comment]
no answer from the requester
